---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octank-invogue
  namespace: user1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octank-invogue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    annotations:
      sidecar.istio.io/inject: "true"
    metadata:
      labels:
        app: octank-invogue
    spec:
      containers:
      - name: octank-invogue
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
